// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_user_data_rpc.proto

package grpc_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserDataRequest struct {
	Pid                  uint32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserDataRequest) Reset()         { *m = GetUserDataRequest{} }
func (m *GetUserDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserDataRequest) ProtoMessage()    {}
func (*GetUserDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd0e6eea1cb3136, []int{0}
}

func (m *GetUserDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDataRequest.Unmarshal(m, b)
}
func (m *GetUserDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDataRequest.Marshal(b, m, deterministic)
}
func (m *GetUserDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDataRequest.Merge(m, src)
}
func (m *GetUserDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserDataRequest.Size(m)
}
func (m *GetUserDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDataRequest proto.InternalMessageInfo

func (m *GetUserDataRequest) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type GetUserDataResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Pid                  uint32   `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	AccessLevel          uint32   `protobuf:"varint,4,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	ServerAccessLevel    string   `protobuf:"bytes,5,opt,name=server_access_level,json=serverAccessLevel,proto3" json:"server_access_level,omitempty"`
	Mii                  *Mii     `protobuf:"bytes,6,opt,name=mii,proto3" json:"mii,omitempty"`
	CreationDate         string   `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Birthdate            string   `protobuf:"bytes,8,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Gender               string   `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Country              string   `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	Language             string   `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	EmailAddress         string   `protobuf:"bytes,12,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	TierName             string   `protobuf:"bytes,13,opt,name=tier_name,json=tierName,proto3" json:"tier_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserDataResponse) Reset()         { *m = GetUserDataResponse{} }
func (m *GetUserDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserDataResponse) ProtoMessage()    {}
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd0e6eea1cb3136, []int{1}
}

func (m *GetUserDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDataResponse.Unmarshal(m, b)
}
func (m *GetUserDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDataResponse.Marshal(b, m, deterministic)
}
func (m *GetUserDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDataResponse.Merge(m, src)
}
func (m *GetUserDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserDataResponse.Size(m)
}
func (m *GetUserDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDataResponse proto.InternalMessageInfo

func (m *GetUserDataResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *GetUserDataResponse) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *GetUserDataResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserDataResponse) GetAccessLevel() uint32 {
	if m != nil {
		return m.AccessLevel
	}
	return 0
}

func (m *GetUserDataResponse) GetServerAccessLevel() string {
	if m != nil {
		return m.ServerAccessLevel
	}
	return ""
}

func (m *GetUserDataResponse) GetMii() *Mii {
	if m != nil {
		return m.Mii
	}
	return nil
}

func (m *GetUserDataResponse) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

func (m *GetUserDataResponse) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *GetUserDataResponse) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *GetUserDataResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *GetUserDataResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetUserDataResponse) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *GetUserDataResponse) GetTierName() string {
	if m != nil {
		return m.TierName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserDataRequest)(nil), "account.GetUserDataRequest")
	proto.RegisterType((*GetUserDataResponse)(nil), "account.GetUserDataResponse")
}

func init() {
	proto.RegisterFile("get_user_data_rpc.proto", fileDescriptor_3bd0e6eea1cb3136)
}

var fileDescriptor_3bd0e6eea1cb3136 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0xc9, 0xcb, 0x7b, 0x6d, 0x73, 0x9b, 0xf2, 0x5e, 0xa7, 0xf0, 0x1c, 0xaa, 0x48, 0xad,
	0x20, 0x5d, 0x45, 0xd0, 0xa5, 0xab, 0x4a, 0xc1, 0x8d, 0xba, 0x08, 0xb8, 0x71, 0x33, 0xdc, 0x26,
	0x97, 0x38, 0x90, 0x7f, 0xce, 0x4c, 0x0a, 0x7e, 0x1e, 0xbf, 0xa8, 0xcc, 0x4c, 0x53, 0xed, 0x2e,
	0xe7, 0x77, 0x4f, 0x4e, 0xee, 0x3d, 0x81, 0x93, 0x82, 0x8c, 0xe8, 0x34, 0x29, 0x91, 0xa3, 0x41,
	0xa1, 0xda, 0x2c, 0x69, 0x55, 0x63, 0x1a, 0x36, 0xc4, 0x2c, 0x6b, 0xba, 0xda, 0xcc, 0xa3, 0x4a,
	0x4a, 0xcf, 0x96, 0x57, 0xc0, 0x1e, 0xc8, 0xbc, 0x68, 0x52, 0x1b, 0x34, 0x98, 0xd2, 0x7b, 0x47,
	0xda, 0xb0, 0x7f, 0x10, 0xb6, 0x32, 0xe7, 0xc1, 0x22, 0x58, 0x4d, 0x52, 0xfb, 0xb8, 0xfc, 0x0c,
	0x61, 0x76, 0x64, 0xd4, 0x6d, 0x53, 0x6b, 0x62, 0x1c, 0x86, 0x39, 0x95, 0x64, 0xc8, 0xbb, 0x47,
	0x69, 0x2f, 0xfb, 0x8c, 0x5f, 0x87, 0x0c, 0x36, 0x87, 0x91, 0x5d, 0xab, 0xc6, 0x8a, 0x78, 0xb8,
	0x08, 0x56, 0x51, 0x7a, 0xd0, 0xec, 0x02, 0x62, 0xcc, 0x32, 0xd2, 0x5a, 0x94, 0xb4, 0xa3, 0x92,
	0xff, 0x76, 0xaf, 0x8d, 0x3d, 0x7b, 0xb4, 0x88, 0x25, 0x30, 0xd3, 0xa4, 0x76, 0xa4, 0xc4, 0x91,
	0xf3, 0x8f, 0x4b, 0x9a, 0xfa, 0xd1, 0xfa, 0x87, 0xff, 0x1c, 0xc2, 0x4a, 0x4a, 0x3e, 0x58, 0x04,
	0xab, 0xf1, 0x4d, 0x9c, 0xec, 0x8f, 0x4f, 0x9e, 0xa4, 0x4c, 0xed, 0x80, 0x5d, 0xc2, 0x24, 0x53,
	0x84, 0x46, 0x36, 0xb5, 0x6d, 0x8a, 0xf8, 0xd0, 0x25, 0xc5, 0x3d, 0xdc, 0xa0, 0x21, 0x76, 0x06,
	0xd1, 0x56, 0x2a, 0xf3, 0xe6, 0x0c, 0x23, 0x67, 0xf8, 0x06, 0xec, 0x3f, 0x0c, 0x0a, 0xaa, 0x73,
	0x52, 0x3c, 0x72, 0xa3, 0xbd, 0xb2, 0xad, 0xb8, 0x8f, 0xa9, 0x0f, 0x0e, 0x6e, 0xd0, 0x4b, 0xdb,
	0x41, 0x89, 0x75, 0xd1, 0x61, 0x41, 0x7c, 0xec, 0x3b, 0xe8, 0xb5, 0x5d, 0x88, 0x2a, 0x94, 0xa5,
	0xc0, 0x3c, 0x57, 0xa4, 0x35, 0x8f, 0xfd, 0x42, 0x0e, 0xae, 0x3d, 0x63, 0xa7, 0x10, 0x19, 0x49,
	0x4a, 0xb8, 0x16, 0x27, 0x3e, 0xc1, 0x82, 0x67, 0xac, 0xe8, 0x7e, 0xfa, 0xfa, 0x37, 0xb9, 0xbe,
	0x2b, 0x54, 0x9b, 0x89, 0xfd, 0xb9, 0xdb, 0x81, 0xfb, 0xcf, 0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x15, 0x13, 0x0c, 0xae, 0x16, 0x02, 0x00, 0x00,
}
