// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_basic_user_data_rpc.proto

package grpc_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBasicUserDataRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBasicUserDataRequest) Reset()         { *m = GetBasicUserDataRequest{} }
func (m *GetBasicUserDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetBasicUserDataRequest) ProtoMessage()    {}
func (*GetBasicUserDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_914c261044d6678b, []int{0}
}

func (m *GetBasicUserDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBasicUserDataRequest.Unmarshal(m, b)
}
func (m *GetBasicUserDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBasicUserDataRequest.Marshal(b, m, deterministic)
}
func (m *GetBasicUserDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBasicUserDataRequest.Merge(m, src)
}
func (m *GetBasicUserDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetBasicUserDataRequest.Size(m)
}
func (m *GetBasicUserDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBasicUserDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBasicUserDataRequest proto.InternalMessageInfo

func (m *GetBasicUserDataRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetBasicUserDataResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AccessLevel          int32    `protobuf:"zigzag32,2,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	Mii                  *Mii     `protobuf:"bytes,3,opt,name=mii,proto3" json:"mii,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBasicUserDataResponse) Reset()         { *m = GetBasicUserDataResponse{} }
func (m *GetBasicUserDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetBasicUserDataResponse) ProtoMessage()    {}
func (*GetBasicUserDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_914c261044d6678b, []int{1}
}

func (m *GetBasicUserDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBasicUserDataResponse.Unmarshal(m, b)
}
func (m *GetBasicUserDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBasicUserDataResponse.Marshal(b, m, deterministic)
}
func (m *GetBasicUserDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBasicUserDataResponse.Merge(m, src)
}
func (m *GetBasicUserDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetBasicUserDataResponse.Size(m)
}
func (m *GetBasicUserDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBasicUserDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBasicUserDataResponse proto.InternalMessageInfo

func (m *GetBasicUserDataResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetBasicUserDataResponse) GetAccessLevel() int32 {
	if m != nil {
		return m.AccessLevel
	}
	return 0
}

func (m *GetBasicUserDataResponse) GetMii() *Mii {
	if m != nil {
		return m.Mii
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBasicUserDataRequest)(nil), "account.GetBasicUserDataRequest")
	proto.RegisterType((*GetBasicUserDataResponse)(nil), "account.GetBasicUserDataResponse")
}

func init() {
	proto.RegisterFile("get_basic_user_data_rpc.proto", fileDescriptor_914c261044d6678b)
}

var fileDescriptor_914c261044d6678b = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x4f, 0x2d, 0x89,
	0x4f, 0x4a, 0x2c, 0xce, 0x4c, 0x8e, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0x4f, 0x49, 0x2c, 0x49, 0x8c,
	0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4c, 0x4e, 0xce, 0x2f,
	0xcd, 0x2b, 0x91, 0xe2, 0xcc, 0xcd, 0xcc, 0x84, 0x88, 0x29, 0x99, 0x72, 0x89, 0xbb, 0xa7, 0x96,
	0x38, 0x81, 0xf4, 0x84, 0x16, 0xa7, 0x16, 0xb9, 0x24, 0x96, 0x24, 0x06, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0x49, 0x71, 0x71, 0x80, 0x4c, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x95, 0x2a, 0xb9, 0x24, 0x30, 0xb5, 0x15, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0xe2, 0xd3, 0x27, 0xa4, 0xc8, 0xc5, 0x93, 0x98, 0x9c, 0x9c, 0x5a, 0x5c, 0x1c, 0x9f, 0x93,
	0x5a, 0x96, 0x9a, 0x23, 0xc1, 0xa4, 0xc0, 0xa8, 0x21, 0x18, 0xc4, 0x0d, 0x11, 0xf3, 0x01, 0x09,
	0x09, 0xc9, 0x71, 0x31, 0xe7, 0x66, 0x66, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe8,
	0x41, 0xdd, 0xac, 0xe7, 0x9b, 0x99, 0x19, 0x04, 0x92, 0x70, 0x12, 0x8c, 0xe2, 0xd7, 0xd3, 0xb7,
	0x4e, 0x2f, 0x2a, 0x48, 0x8e, 0x87, 0xca, 0x25, 0xb1, 0x81, 0xfd, 0x62, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xc6, 0xfc, 0xd4, 0x74, 0x00, 0x01, 0x00, 0x00,
}
