// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login_rpc.proto

package grpc_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885dfdd9fa1d67a1, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	ExpiresIn            uint32   `protobuf:"varint,1,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885dfdd9fa1d67a1, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetExpiresIn() uint32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *LoginResponse) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "account.LoginResponse")
}

func init() {
	proto.RegisterFile("login_rpc.proto", fileDescriptor_885dfdd9fa1d67a1)
}

var fileDescriptor_885dfdd9fa1d67a1 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x31, 0x4b, 0xc0, 0x30,
	0x10, 0x46, 0xa9, 0x8a, 0xda, 0xb3, 0xa5, 0x98, 0xa9, 0x08, 0x82, 0xd6, 0xc5, 0xa9, 0x0e, 0x8e,
	0x6e, 0x0e, 0x82, 0xe0, 0x54, 0x3a, 0xb9, 0x84, 0x18, 0xcf, 0x5a, 0xd4, 0xe4, 0xbc, 0x4b, 0xd1,
	0xfe, 0x10, 0xff, 0xaf, 0x24, 0x8d, 0x8e, 0xf7, 0xde, 0xe3, 0x83, 0x04, 0x9a, 0x77, 0x3f, 0xcd,
	0x4e, 0x33, 0xd9, 0x9e, 0xd8, 0x07, 0xaf, 0x0e, 0x8c, 0xb5, 0x7e, 0x71, 0xa1, 0xbb, 0x83, 0xea,
	0x21, 0xba, 0x01, 0x3f, 0x17, 0x94, 0xa0, 0x4e, 0xe0, 0x70, 0x11, 0x64, 0x67, 0x3e, 0xb0, 0x2d,
	0xce, 0x8a, 0xcb, 0x72, 0xf8, 0xbf, 0xa3, 0x23, 0x23, 0xf2, 0xe5, 0xf9, 0xb9, 0xdd, 0xd9, 0xdc,
	0xdf, 0xdd, 0xfd, 0x14, 0x50, 0xe7, 0x21, 0x21, 0xef, 0x04, 0xd5, 0x29, 0x00, 0x7e, 0xd3, 0xcc,
	0x28, 0x7a, 0x76, 0x69, 0xab, 0x1e, 0xca, 0x4c, 0xee, 0x5d, 0xd4, 0xc1, 0xbf, 0xa1, 0xd3, 0x61,
	0x25, 0xcc, 0x73, 0x65, 0x22, 0xe3, 0x4a, 0xa8, 0xce, 0xa1, 0x32, 0xd6, 0xa2, 0x88, 0x4e, 0xac,
	0xdd, 0x4d, 0xc1, 0xd1, 0xc6, 0xc6, 0x88, 0xd4, 0x05, 0xd4, 0x8c, 0x2f, 0x8c, 0xf2, 0x9a, 0x9b,
	0xbd, 0xd4, 0x54, 0x19, 0xa6, 0xe8, 0xf6, 0xf8, 0xb1, 0xe9, 0xaf, 0x6e, 0x26, 0x26, 0xab, 0xf3,
	0x93, 0x9f, 0xf6, 0xd3, 0x17, 0x5c, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x76, 0x7f, 0xe3,
	0x15, 0x01, 0x00, 0x00,
}
