// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mii.proto

package grpc_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mii struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mii) Reset()         { *m = Mii{} }
func (m *Mii) String() string { return proto.CompactTextString(m) }
func (*Mii) ProtoMessage()    {}
func (*Mii) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f2abb32b0304e72, []int{0}
}

func (m *Mii) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mii.Unmarshal(m, b)
}
func (m *Mii) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mii.Marshal(b, m, deterministic)
}
func (m *Mii) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mii.Merge(m, src)
}
func (m *Mii) XXX_Size() int {
	return xxx_messageInfo_Mii.Size(m)
}
func (m *Mii) XXX_DiscardUnknown() {
	xxx_messageInfo_Mii.DiscardUnknown(m)
}

var xxx_messageInfo_Mii proto.InternalMessageInfo

func (m *Mii) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mii) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Mii) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Mii)(nil), "account.Mii")
}

func init() {
	proto.RegisterFile("mii.proto", fileDescriptor_2f2abb32b0304e72)
}

var fileDescriptor_2f2abb32b0304e72 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xcd, 0xcc, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x51, 0xb2,
	0xe7, 0x62, 0xf6, 0xcd, 0xcc, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x29, 0x89, 0x25, 0x89, 0x12, 0x4c, 0x10, 0x31,
	0x10, 0x5b, 0x48, 0x80, 0x8b, 0xb9, 0xb4, 0x28, 0x47, 0x82, 0x19, 0x2c, 0x04, 0x62, 0x3a, 0x09,
	0x46, 0xf1, 0xeb, 0xe9, 0x5b, 0xa7, 0x17, 0x15, 0x24, 0xc7, 0x43, 0xcd, 0x4c, 0x62, 0x03, 0xdb,
	0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x57, 0x78, 0x10, 0xfa, 0x70, 0x00, 0x00, 0x00,
}
