// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accept_friend_request_rpc.proto

package grpc_friends

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AcceptFriendRequestRequest struct {
	Accept               uint64   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptFriendRequestRequest) Reset()         { *m = AcceptFriendRequestRequest{} }
func (m *AcceptFriendRequestRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptFriendRequestRequest) ProtoMessage()    {}
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc28e8b506ad3010, []int{0}
}

func (m *AcceptFriendRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptFriendRequestRequest.Unmarshal(m, b)
}
func (m *AcceptFriendRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptFriendRequestRequest.Marshal(b, m, deterministic)
}
func (m *AcceptFriendRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptFriendRequestRequest.Merge(m, src)
}
func (m *AcceptFriendRequestRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptFriendRequestRequest.Size(m)
}
func (m *AcceptFriendRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptFriendRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptFriendRequestRequest proto.InternalMessageInfo

func (m *AcceptFriendRequestRequest) GetAccept() uint64 {
	if m != nil {
		return m.Accept
	}
	return 0
}

type AcceptFriendRequestResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptFriendRequestResponse) Reset()         { *m = AcceptFriendRequestResponse{} }
func (m *AcceptFriendRequestResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptFriendRequestResponse) ProtoMessage()    {}
func (*AcceptFriendRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc28e8b506ad3010, []int{1}
}

func (m *AcceptFriendRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptFriendRequestResponse.Unmarshal(m, b)
}
func (m *AcceptFriendRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptFriendRequestResponse.Marshal(b, m, deterministic)
}
func (m *AcceptFriendRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptFriendRequestResponse.Merge(m, src)
}
func (m *AcceptFriendRequestResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptFriendRequestResponse.Size(m)
}
func (m *AcceptFriendRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptFriendRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptFriendRequestResponse proto.InternalMessageInfo

func (m *AcceptFriendRequestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*AcceptFriendRequestRequest)(nil), "friends.AcceptFriendRequestRequest")
	proto.RegisterType((*AcceptFriendRequestResponse)(nil), "friends.AcceptFriendRequestResponse")
}

func init() {
	proto.RegisterFile("accept_friend_request_rpc.proto", fileDescriptor_fc28e8b506ad3010)
}

var fileDescriptor_fc28e8b506ad3010 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x4c, 0x4e, 0x4e,
	0x2d, 0x28, 0x89, 0x4f, 0x2b, 0xca, 0x4c, 0xcd, 0x4b, 0x89, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x89, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0xc8, 0x14,
	0x2b, 0x99, 0x70, 0x49, 0x39, 0x82, 0xd5, 0xba, 0x81, 0x05, 0x82, 0x20, 0x2a, 0xa1, 0x94, 0x90,
	0x18, 0x17, 0x1b, 0xc4, 0x24, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x28, 0x4f, 0xc9, 0x9c,
	0x4b, 0x1a, 0xab, 0xae, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0xe2, 0xd2,
	0xe4, 0xe4, 0xd4, 0xe2, 0x62, 0xb0, 0x3e, 0x8e, 0x20, 0x18, 0xd7, 0x49, 0x30, 0x8a, 0x5f, 0x4f,
	0xdf, 0x3a, 0xbd, 0xa8, 0x20, 0x19, 0xea, 0xb6, 0xe2, 0x24, 0x36, 0xb0, 0x8b, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x9d, 0x50, 0x32, 0x91, 0xb4, 0x00, 0x00, 0x00,
}
