// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: friends_service.proto

package grpc_friends

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Friends_SendUserNotificationWiiU_FullMethodName      = "/friends.Friends/SendUserNotificationWiiU"
	Friends_GetUserFriendPIDs_FullMethodName             = "/friends.Friends/GetUserFriendPIDs"
	Friends_SendUserFriendRequest_FullMethodName         = "/friends.Friends/SendUserFriendRequest"
	Friends_GetUserFriendRequestsIncoming_FullMethodName = "/friends.Friends/GetUserFriendRequestsIncoming"
	Friends_AcceptFriendRequest_FullMethodName           = "/friends.Friends/AcceptFriendRequest"
	Friends_DenyFriendRequest_FullMethodName             = "/friends.Friends/DenyFriendRequest"
)

// FriendsClient is the client API for Friends service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendsClient interface {
	SendUserNotificationWiiU(ctx context.Context, in *SendUserNotificationWiiURequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUserFriendPIDs(ctx context.Context, in *GetUserFriendPIDsRequest, opts ...grpc.CallOption) (*GetUserFriendPIDsResponse, error)
	SendUserFriendRequest(ctx context.Context, in *SendUserFriendRequestRequest, opts ...grpc.CallOption) (*SendUserFriendRequestResponse, error)
	GetUserFriendRequestsIncoming(ctx context.Context, in *GetUserFriendRequestsIncomingRequest, opts ...grpc.CallOption) (*GetUserFriendRequestsIncomingResponse, error)
	AcceptFriendRequest(ctx context.Context, in *AcceptFriendRequestRequest, opts ...grpc.CallOption) (*AcceptFriendRequestResponse, error)
	DenyFriendRequest(ctx context.Context, in *DenyFriendRequestRequest, opts ...grpc.CallOption) (*DenyFriendRequestResponse, error)
}

type friendsClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendsClient(cc grpc.ClientConnInterface) FriendsClient {
	return &friendsClient{cc}
}

func (c *friendsClient) SendUserNotificationWiiU(ctx context.Context, in *SendUserNotificationWiiURequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Friends_SendUserNotificationWiiU_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) GetUserFriendPIDs(ctx context.Context, in *GetUserFriendPIDsRequest, opts ...grpc.CallOption) (*GetUserFriendPIDsResponse, error) {
	out := new(GetUserFriendPIDsResponse)
	err := c.cc.Invoke(ctx, Friends_GetUserFriendPIDs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) SendUserFriendRequest(ctx context.Context, in *SendUserFriendRequestRequest, opts ...grpc.CallOption) (*SendUserFriendRequestResponse, error) {
	out := new(SendUserFriendRequestResponse)
	err := c.cc.Invoke(ctx, Friends_SendUserFriendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) GetUserFriendRequestsIncoming(ctx context.Context, in *GetUserFriendRequestsIncomingRequest, opts ...grpc.CallOption) (*GetUserFriendRequestsIncomingResponse, error) {
	out := new(GetUserFriendRequestsIncomingResponse)
	err := c.cc.Invoke(ctx, Friends_GetUserFriendRequestsIncoming_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) AcceptFriendRequest(ctx context.Context, in *AcceptFriendRequestRequest, opts ...grpc.CallOption) (*AcceptFriendRequestResponse, error) {
	out := new(AcceptFriendRequestResponse)
	err := c.cc.Invoke(ctx, Friends_AcceptFriendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) DenyFriendRequest(ctx context.Context, in *DenyFriendRequestRequest, opts ...grpc.CallOption) (*DenyFriendRequestResponse, error) {
	out := new(DenyFriendRequestResponse)
	err := c.cc.Invoke(ctx, Friends_DenyFriendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendsServer is the server API for Friends service.
// All implementations must embed UnimplementedFriendsServer
// for forward compatibility
type FriendsServer interface {
	SendUserNotificationWiiU(context.Context, *SendUserNotificationWiiURequest) (*empty.Empty, error)
	GetUserFriendPIDs(context.Context, *GetUserFriendPIDsRequest) (*GetUserFriendPIDsResponse, error)
	SendUserFriendRequest(context.Context, *SendUserFriendRequestRequest) (*SendUserFriendRequestResponse, error)
	GetUserFriendRequestsIncoming(context.Context, *GetUserFriendRequestsIncomingRequest) (*GetUserFriendRequestsIncomingResponse, error)
	AcceptFriendRequest(context.Context, *AcceptFriendRequestRequest) (*AcceptFriendRequestResponse, error)
	DenyFriendRequest(context.Context, *DenyFriendRequestRequest) (*DenyFriendRequestResponse, error)
	mustEmbedUnimplementedFriendsServer()
}

// UnimplementedFriendsServer must be embedded to have forward compatible implementations.
type UnimplementedFriendsServer struct {
}

func (UnimplementedFriendsServer) SendUserNotificationWiiU(context.Context, *SendUserNotificationWiiURequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUserNotificationWiiU not implemented")
}
func (UnimplementedFriendsServer) GetUserFriendPIDs(context.Context, *GetUserFriendPIDsRequest) (*GetUserFriendPIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFriendPIDs not implemented")
}
func (UnimplementedFriendsServer) SendUserFriendRequest(context.Context, *SendUserFriendRequestRequest) (*SendUserFriendRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUserFriendRequest not implemented")
}
func (UnimplementedFriendsServer) GetUserFriendRequestsIncoming(context.Context, *GetUserFriendRequestsIncomingRequest) (*GetUserFriendRequestsIncomingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFriendRequestsIncoming not implemented")
}
func (UnimplementedFriendsServer) AcceptFriendRequest(context.Context, *AcceptFriendRequestRequest) (*AcceptFriendRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptFriendRequest not implemented")
}
func (UnimplementedFriendsServer) DenyFriendRequest(context.Context, *DenyFriendRequestRequest) (*DenyFriendRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenyFriendRequest not implemented")
}
func (UnimplementedFriendsServer) mustEmbedUnimplementedFriendsServer() {}

// UnsafeFriendsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendsServer will
// result in compilation errors.
type UnsafeFriendsServer interface {
	mustEmbedUnimplementedFriendsServer()
}

func RegisterFriendsServer(s grpc.ServiceRegistrar, srv FriendsServer) {
	s.RegisterService(&Friends_ServiceDesc, srv)
}

func _Friends_SendUserNotificationWiiU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserNotificationWiiURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).SendUserNotificationWiiU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_SendUserNotificationWiiU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).SendUserNotificationWiiU(ctx, req.(*SendUserNotificationWiiURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_GetUserFriendPIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFriendPIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).GetUserFriendPIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_GetUserFriendPIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).GetUserFriendPIDs(ctx, req.(*GetUserFriendPIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_SendUserFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).SendUserFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_SendUserFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).SendUserFriendRequest(ctx, req.(*SendUserFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_GetUserFriendRequestsIncoming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFriendRequestsIncomingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).GetUserFriendRequestsIncoming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_GetUserFriendRequestsIncoming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).GetUserFriendRequestsIncoming(ctx, req.(*GetUserFriendRequestsIncomingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_AcceptFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).AcceptFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_AcceptFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).AcceptFriendRequest(ctx, req.(*AcceptFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_DenyFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).DenyFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_DenyFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).DenyFriendRequest(ctx, req.(*DenyFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Friends_ServiceDesc is the grpc.ServiceDesc for Friends service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Friends_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friends.Friends",
	HandlerType: (*FriendsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendUserNotificationWiiU",
			Handler:    _Friends_SendUserNotificationWiiU_Handler,
		},
		{
			MethodName: "GetUserFriendPIDs",
			Handler:    _Friends_GetUserFriendPIDs_Handler,
		},
		{
			MethodName: "SendUserFriendRequest",
			Handler:    _Friends_SendUserFriendRequest_Handler,
		},
		{
			MethodName: "GetUserFriendRequestsIncoming",
			Handler:    _Friends_GetUserFriendRequestsIncoming_Handler,
		},
		{
			MethodName: "AcceptFriendRequest",
			Handler:    _Friends_AcceptFriendRequest_Handler,
		},
		{
			MethodName: "DenyFriendRequest",
			Handler:    _Friends_DenyFriendRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "friends_service.proto",
}
