// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friend_request.proto

package grpc_friends

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FriendRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender               uint32   `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient            uint32   `protobuf:"varint,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Sent                 uint64   `protobuf:"varint,4,opt,name=sent,proto3" json:"sent,omitempty"`
	Expires              uint64   `protobuf:"varint,5,opt,name=expires,proto3" json:"expires,omitempty"`
	Message              string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequest) Reset()         { *m = FriendRequest{} }
func (m *FriendRequest) String() string { return proto.CompactTextString(m) }
func (*FriendRequest) ProtoMessage()    {}
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7112050df3d0ca77, []int{0}
}

func (m *FriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequest.Unmarshal(m, b)
}
func (m *FriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequest.Marshal(b, m, deterministic)
}
func (m *FriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequest.Merge(m, src)
}
func (m *FriendRequest) XXX_Size() int {
	return xxx_messageInfo_FriendRequest.Size(m)
}
func (m *FriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequest proto.InternalMessageInfo

func (m *FriendRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FriendRequest) GetSender() uint32 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *FriendRequest) GetRecipient() uint32 {
	if m != nil {
		return m.Recipient
	}
	return 0
}

func (m *FriendRequest) GetSent() uint64 {
	if m != nil {
		return m.Sent
	}
	return 0
}

func (m *FriendRequest) GetExpires() uint64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *FriendRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FriendRequest)(nil), "friends.FriendRequest")
}

func init() {
	proto.RegisterFile("friend_request.proto", fileDescriptor_7112050df3d0ca77)
}

var fileDescriptor_7112050df3d0ca77 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2b, 0xca, 0x4c,
	0xcd, 0x4b, 0x89, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x87, 0x88, 0x16, 0x2b, 0xcd, 0x65, 0xe4, 0xe2, 0x75, 0x03, 0xb3, 0x83, 0x20, 0x0a,
	0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0x98, 0x32, 0x53,
	0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x53, 0xf3, 0x52, 0x52, 0x8b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78,
	0x83, 0xa0, 0x3c, 0x21, 0x19, 0x2e, 0xce, 0xa2, 0xd4, 0xe4, 0xcc, 0x82, 0xcc, 0xd4, 0xbc, 0x12,
	0x09, 0x66, 0xb0, 0x14, 0x42, 0x40, 0x48, 0x88, 0x8b, 0xa5, 0x18, 0x24, 0xc1, 0x02, 0x36, 0x07,
	0xcc, 0x16, 0x92, 0xe0, 0x62, 0x4f, 0xad, 0x28, 0xc8, 0x2c, 0x4a, 0x2d, 0x96, 0x60, 0x05, 0x0b,
	0xc3, 0xb8, 0x20, 0x99, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x36, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x18, 0xd7, 0x49, 0x30, 0x8a, 0x5f, 0x4f, 0xdf, 0x3a, 0xbd, 0xa8, 0x20, 0x39, 0x1e,
	0xea, 0xe4, 0x24, 0x36, 0xb0, 0x17, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xab, 0xb8, 0xb2,
	0xfa, 0xda, 0x00, 0x00, 0x00,
}
