// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_user_friend_requests_incoming_rpc.proto

package grpc_friends

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserFriendRequestsIncomingRequest struct {
	Pid                  uint32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserFriendRequestsIncomingRequest) Reset()         { *m = GetUserFriendRequestsIncomingRequest{} }
func (m *GetUserFriendRequestsIncomingRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserFriendRequestsIncomingRequest) ProtoMessage()    {}
func (*GetUserFriendRequestsIncomingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1907fbaddc25008a, []int{0}
}

func (m *GetUserFriendRequestsIncomingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserFriendRequestsIncomingRequest.Unmarshal(m, b)
}
func (m *GetUserFriendRequestsIncomingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserFriendRequestsIncomingRequest.Marshal(b, m, deterministic)
}
func (m *GetUserFriendRequestsIncomingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserFriendRequestsIncomingRequest.Merge(m, src)
}
func (m *GetUserFriendRequestsIncomingRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserFriendRequestsIncomingRequest.Size(m)
}
func (m *GetUserFriendRequestsIncomingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserFriendRequestsIncomingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserFriendRequestsIncomingRequest proto.InternalMessageInfo

func (m *GetUserFriendRequestsIncomingRequest) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type GetUserFriendRequestsIncomingResponse struct {
	FriendRequests       []*FriendRequest `protobuf:"bytes,1,rep,name=friend_requests,json=friendRequests,proto3" json:"friend_requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetUserFriendRequestsIncomingResponse) Reset()         { *m = GetUserFriendRequestsIncomingResponse{} }
func (m *GetUserFriendRequestsIncomingResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserFriendRequestsIncomingResponse) ProtoMessage()    {}
func (*GetUserFriendRequestsIncomingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1907fbaddc25008a, []int{1}
}

func (m *GetUserFriendRequestsIncomingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserFriendRequestsIncomingResponse.Unmarshal(m, b)
}
func (m *GetUserFriendRequestsIncomingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserFriendRequestsIncomingResponse.Marshal(b, m, deterministic)
}
func (m *GetUserFriendRequestsIncomingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserFriendRequestsIncomingResponse.Merge(m, src)
}
func (m *GetUserFriendRequestsIncomingResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserFriendRequestsIncomingResponse.Size(m)
}
func (m *GetUserFriendRequestsIncomingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserFriendRequestsIncomingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserFriendRequestsIncomingResponse proto.InternalMessageInfo

func (m *GetUserFriendRequestsIncomingResponse) GetFriendRequests() []*FriendRequest {
	if m != nil {
		return m.FriendRequests
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserFriendRequestsIncomingRequest)(nil), "friends.GetUserFriendRequestsIncomingRequest")
	proto.RegisterType((*GetUserFriendRequestsIncomingResponse)(nil), "friends.GetUserFriendRequestsIncomingResponse")
}

func init() {
	proto.RegisterFile("get_user_friend_requests_incoming_rpc.proto", fileDescriptor_1907fbaddc25008a)
}

var fileDescriptor_1907fbaddc25008a = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4e, 0x4f, 0x2d, 0x89,
	0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0x4f, 0x2b, 0xca, 0x4c, 0xcd, 0x4b, 0x89, 0x2f, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x29, 0x8e, 0xcf, 0xcc, 0x4b, 0xce, 0xcf, 0xcd, 0xcc, 0x4b, 0x8f, 0x2f, 0x2a,
	0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0xa8, 0x29, 0x96, 0x12, 0x41, 0x55,
	0x0c, 0x91, 0x56, 0xb2, 0xe0, 0x52, 0x71, 0x4f, 0x2d, 0x09, 0x2d, 0x4e, 0x2d, 0x72, 0x03, 0x4b,
	0x07, 0x41, 0x8d, 0xf2, 0x84, 0x9a, 0x04, 0xe5, 0x0b, 0x09, 0x70, 0x31, 0x17, 0x64, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x81, 0x98, 0x4a, 0x19, 0x5c, 0xaa, 0x04, 0x74, 0x16, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xd9, 0x73, 0xf1, 0xa3, 0xb9, 0x53, 0x82, 0x51, 0x81, 0x59, 0x83,
	0xdb, 0x48, 0x4c, 0x0f, 0xea, 0x36, 0x3d, 0x14, 0x13, 0x82, 0xf8, 0xd2, 0x50, 0x0c, 0x74, 0x12,
	0x8c, 0xe2, 0xd7, 0xd3, 0xb7, 0x4e, 0x2f, 0x2a, 0x48, 0x86, 0x7a, 0xb8, 0x38, 0x89, 0x0d, 0xec,
	0x7a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x37, 0xdb, 0x18, 0x0b, 0x01, 0x00, 0x00,
}
