// Code generated by protoc-gen-go. DO NOT EDIT.
// source: send_user_friend_request_rpc.proto

package grpc_friends

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendUserFriendRequestRequest struct {
	Sender               uint32   `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient            uint32   `protobuf:"varint,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendUserFriendRequestRequest) Reset()         { *m = SendUserFriendRequestRequest{} }
func (m *SendUserFriendRequestRequest) String() string { return proto.CompactTextString(m) }
func (*SendUserFriendRequestRequest) ProtoMessage()    {}
func (*SendUserFriendRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55b636fab61ffa51, []int{0}
}

func (m *SendUserFriendRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendUserFriendRequestRequest.Unmarshal(m, b)
}
func (m *SendUserFriendRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendUserFriendRequestRequest.Marshal(b, m, deterministic)
}
func (m *SendUserFriendRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendUserFriendRequestRequest.Merge(m, src)
}
func (m *SendUserFriendRequestRequest) XXX_Size() int {
	return xxx_messageInfo_SendUserFriendRequestRequest.Size(m)
}
func (m *SendUserFriendRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendUserFriendRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendUserFriendRequestRequest proto.InternalMessageInfo

func (m *SendUserFriendRequestRequest) GetSender() uint32 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *SendUserFriendRequestRequest) GetRecipient() uint32 {
	if m != nil {
		return m.Recipient
	}
	return 0
}

func (m *SendUserFriendRequestRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendUserFriendRequestResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendUserFriendRequestResponse) Reset()         { *m = SendUserFriendRequestResponse{} }
func (m *SendUserFriendRequestResponse) String() string { return proto.CompactTextString(m) }
func (*SendUserFriendRequestResponse) ProtoMessage()    {}
func (*SendUserFriendRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55b636fab61ffa51, []int{1}
}

func (m *SendUserFriendRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendUserFriendRequestResponse.Unmarshal(m, b)
}
func (m *SendUserFriendRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendUserFriendRequestResponse.Marshal(b, m, deterministic)
}
func (m *SendUserFriendRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendUserFriendRequestResponse.Merge(m, src)
}
func (m *SendUserFriendRequestResponse) XXX_Size() int {
	return xxx_messageInfo_SendUserFriendRequestResponse.Size(m)
}
func (m *SendUserFriendRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendUserFriendRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendUserFriendRequestResponse proto.InternalMessageInfo

func (m *SendUserFriendRequestResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*SendUserFriendRequestRequest)(nil), "friends.SendUserFriendRequestRequest")
	proto.RegisterType((*SendUserFriendRequestResponse)(nil), "friends.SendUserFriendRequestResponse")
}

func init() {
	proto.RegisterFile("send_user_friend_request_rpc.proto", fileDescriptor_55b636fab61ffa51)
}

var fileDescriptor_55b636fab61ffa51 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x4e, 0xcd, 0x4b,
	0x89, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0x4f, 0x2b, 0xca, 0x04, 0xb1, 0x8b, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0xe2, 0x8b, 0x0a, 0x92, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8, 0x21, 0x32,
	0xc5, 0x4a, 0x79, 0x5c, 0x32, 0xc1, 0xa9, 0x79, 0x29, 0xa1, 0xc5, 0xa9, 0x45, 0x6e, 0x60, 0xa1,
	0x20, 0x88, 0x5a, 0x28, 0x25, 0x24, 0xc6, 0xc5, 0x06, 0x32, 0x2e, 0xb5, 0x48, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x37, 0x08, 0xca, 0x13, 0x92, 0xe1, 0xe2, 0x2c, 0x4a, 0x4d, 0xce, 0x2c, 0xc8, 0x4c,
	0xcd, 0x2b, 0x91, 0x60, 0x02, 0x4b, 0x21, 0x04, 0x84, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b,
	0x13, 0xd3, 0x53, 0x25, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x4b, 0x2e, 0x59,
	0x1c, 0xf6, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x82, 0xb4, 0x16, 0x97, 0x26, 0x27, 0xa7, 0x16,
	0x17, 0x83, 0x6d, 0xe4, 0x08, 0x82, 0x71, 0x9d, 0x04, 0xa3, 0xf8, 0xf5, 0xf4, 0xad, 0xd3, 0x8b,
	0x0a, 0x92, 0xa1, 0xfe, 0x2a, 0x4e, 0x62, 0x03, 0xfb, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xf5, 0x95, 0x21, 0x97, 0xf3, 0x00, 0x00, 0x00,
}
