// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: smm_request_post_id_rpc.proto

package miiverse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SMMRequestPostIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseId uint64 `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"` // TODO: Other course/user data?
}

func (x *SMMRequestPostIdRequest) Reset() {
	*x = SMMRequestPostIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smm_request_post_id_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMMRequestPostIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMMRequestPostIdRequest) ProtoMessage() {}

func (x *SMMRequestPostIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smm_request_post_id_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMMRequestPostIdRequest.ProtoReflect.Descriptor instead.
func (*SMMRequestPostIdRequest) Descriptor() ([]byte, []int) {
	return file_smm_request_post_id_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SMMRequestPostIdRequest) GetCourseId() uint64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type SMMRequestPostIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *SMMRequestPostIdResponse) Reset() {
	*x = SMMRequestPostIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_smm_request_post_id_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMMRequestPostIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMMRequestPostIdResponse) ProtoMessage() {}

func (x *SMMRequestPostIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smm_request_post_id_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMMRequestPostIdResponse.ProtoReflect.Descriptor instead.
func (*SMMRequestPostIdResponse) Descriptor() ([]byte, []int) {
	return file_smm_request_post_id_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SMMRequestPostIdResponse) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

var File_smm_request_post_id_rpc_proto protoreflect.FileDescriptor

var file_smm_request_post_id_rpc_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x6d, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6d, 0x69, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x22, 0x36, 0x0a, 0x17, 0x53, 0x4d, 0x4d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x64, 0x22, 0x33, 0x0a, 0x18, 0x53, 0x4d, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x6d, 0x69, 0x69,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_smm_request_post_id_rpc_proto_rawDescOnce sync.Once
	file_smm_request_post_id_rpc_proto_rawDescData = file_smm_request_post_id_rpc_proto_rawDesc
)

func file_smm_request_post_id_rpc_proto_rawDescGZIP() []byte {
	file_smm_request_post_id_rpc_proto_rawDescOnce.Do(func() {
		file_smm_request_post_id_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_smm_request_post_id_rpc_proto_rawDescData)
	})
	return file_smm_request_post_id_rpc_proto_rawDescData
}

var file_smm_request_post_id_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_smm_request_post_id_rpc_proto_goTypes = []interface{}{
	(*SMMRequestPostIdRequest)(nil),  // 0: miiverse.SMMRequestPostIdRequest
	(*SMMRequestPostIdResponse)(nil), // 1: miiverse.SMMRequestPostIdResponse
}
var file_smm_request_post_id_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smm_request_post_id_rpc_proto_init() }
func file_smm_request_post_id_rpc_proto_init() {
	if File_smm_request_post_id_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_smm_request_post_id_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMMRequestPostIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_smm_request_post_id_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMMRequestPostIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_smm_request_post_id_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smm_request_post_id_rpc_proto_goTypes,
		DependencyIndexes: file_smm_request_post_id_rpc_proto_depIdxs,
		MessageInfos:      file_smm_request_post_id_rpc_proto_msgTypes,
	}.Build()
	File_smm_request_post_id_rpc_proto = out.File
	file_smm_request_post_id_rpc_proto_rawDesc = nil
	file_smm_request_post_id_rpc_proto_goTypes = nil
	file_smm_request_post_id_rpc_proto_depIdxs = nil
}
